/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.oficina.project.view.TelaPrincipal.CarrosView;

import com.oficina.project.view.TelaPrincipal.ClienteViews.*;
import com.oficina.project.controller.Clientes.BuscarClienteController;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ComboBoxEditor;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Venicio
 */
public class CadastrarCarrosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarAdmView
     */
    public CadastrarCarrosView() {
        initComponents();
        new com.oficina.project.controller.Carros.CadastrarCarrosController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        CampoMarcaCadastro = new javax.swing.JTextField();
        CampoModeloCadastro = new javax.swing.JTextField();
        LbModeloCadastro = new javax.swing.JLabel();
        LbMarcaCadastro = new javax.swing.JLabel();
        InternaEditarUsuario = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        CampoPesquisar = new javax.swing.JTextField();
        InternaDadosPesquisa = new javax.swing.JInternalFrame();
        LbInfoModelo = new javax.swing.JLabel();
        LbInfoMarca = new javax.swing.JLabel();
        LbInfoDataCadastro = new javax.swing.JLabel();
        LbInfoDataAtualizacao = new javax.swing.JLabel();
        CampoInfoDataAtualizacao = new javax.swing.JTextField();
        CampoInfoDataCadastro = new javax.swing.JTextField();
        CampoInfoModelo = new javax.swing.JTextField();
        CampoInfoCor = new javax.swing.JTextField();
        LbInfoNome2 = new javax.swing.JLabel();
        CampoInfoId = new javax.swing.JTextField();
        LbInfoAno = new javax.swing.JLabel();
        LbInfoCPF = new javax.swing.JLabel();
        CampoInfoAno = new javax.swing.JTextField();
        CampoInfoPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoInfoMarca = new javax.swing.JTextField();
        BtEditar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        IconPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtSalvarCarro = new javax.swing.JButton();
        LbPlacaCadastro = new javax.swing.JLabel();
        LbAnoCadastro = new javax.swing.JLabel();
        CampoPlacaCadastro = new javax.swing.JTextField();
        CampoAnoCadastro = new javax.swing.JTextField();
        InternaResultado = new javax.swing.JInternalFrame();
        LbModeloResultado = new javax.swing.JLabel();
        LbAnoResultado = new javax.swing.JLabel();
        LbMarcaResultado = new javax.swing.JLabel();
        LbPlacaResultado = new javax.swing.JLabel();
        LbNomeResultado5 = new javax.swing.JLabel();
        CampoAnoResultado = new javax.swing.JTextField();
        CampoModeloResultado = new javax.swing.JTextField();
        CampoMarcaResultado = new javax.swing.JTextField();
        CampoResultadoCadastro = new javax.swing.JTextField();
        CampoResultadoPlaca = new javax.swing.JTextField();
        BarraProgresso = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        LbPlacaResultado1 = new javax.swing.JLabel();
        CampoResultadoCor = new javax.swing.JTextField();
        LbIdResultado = new javax.swing.JLabel();
        CampoIdResultado = new javax.swing.JTextField();
        LbCadastrarCor = new javax.swing.JLabel();
        CampoCorCadastrar = new javax.swing.JTextField();
        IconeInformativo = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Carros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        CampoMarcaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoMarcaCadastroActionPerformed(evt);
            }
        });

        LbModeloCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbModeloCadastro.setText("Modelo:");

        LbMarcaCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbMarcaCadastro.setText("Marca:");

        InternaEditarUsuario.setBackground(new java.awt.Color(183, 183, 167));
        InternaEditarUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Carros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14))); // NOI18N
        InternaEditarUsuario.setVisible(true);

        TabelaClientes.setBackground(new java.awt.Color(204, 204, 204));
        TabelaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelaClientes.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Modelo", "Marca", "Ano", "Placa", "Cor", "Data de Cadastro", "Data de Atualização"
            }
        ));
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);

        CampoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisarActionPerformed(evt);
            }
        });

        InternaDadosPesquisa.setBackground(new java.awt.Color(153, 153, 153));
        InternaDadosPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informações de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        InternaDadosPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        InternaDadosPesquisa.setVisible(true);

        LbInfoModelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoModelo.setText("Modelo:");

        LbInfoMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoMarca.setText("Marca:");

        LbInfoDataCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoDataCadastro.setText("Data de Cadastro:");

        LbInfoDataAtualizacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoDataAtualizacao.setText("Data de Atualização:");

        LbInfoNome2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoNome2.setText("ID:");

        LbInfoAno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoAno.setText("Ano:");

        LbInfoCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoCPF.setText("PLaca:");

        CampoInfoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInfoAnoActionPerformed(evt);
            }
        });

        CampoInfoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInfoPlacaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cor:");

        javax.swing.GroupLayout InternaDadosPesquisaLayout = new javax.swing.GroupLayout(InternaDadosPesquisa.getContentPane());
        InternaDadosPesquisa.getContentPane().setLayout(InternaDadosPesquisaLayout);
        InternaDadosPesquisaLayout.setHorizontalGroup(
            InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbInfoCPF)
                            .addComponent(LbInfoAno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoInfoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 522, Short.MAX_VALUE))
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addComponent(LbInfoModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoInfoModelo)
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(LbInfoNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoInfoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(279, 279, 279))
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LbInfoDataAtualizacao)
                                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(LbInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CampoInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CampoInfoDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(LbInfoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CampoInfoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CampoInfoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        InternaDadosPesquisaLayout.setVerticalGroup(
            InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoNome2)
                    .addComponent(CampoInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoModelo)
                    .addComponent(CampoInfoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(CampoInfoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoMarca)
                    .addComponent(CampoInfoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbInfoAno)
                    .addComponent(CampoInfoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoCPF)
                    .addComponent(CampoInfoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoDataCadastro)
                    .addComponent(CampoInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoDataAtualizacao)
                    .addComponent(CampoInfoDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        IconPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Editar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Excluir");

        javax.swing.GroupLayout InternaEditarUsuarioLayout = new javax.swing.GroupLayout(InternaEditarUsuario.getContentPane());
        InternaEditarUsuario.getContentPane().setLayout(InternaEditarUsuarioLayout);
        InternaEditarUsuarioLayout.setHorizontalGroup(
            InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel1)
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel2))
                                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(BtEditar)
                                        .addGap(48, 48, 48)
                                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(143, 143, 143))
                            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                .addComponent(IconPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(InternaDadosPesquisa)))
                .addContainerGap())
        );
        InternaEditarUsuarioLayout.setVerticalGroup(
            InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconPesquisar))
                        .addGap(26, 26, 26)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtEditar)
                            .addComponent(BtExcluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InternaDadosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtSalvarCarro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtSalvarCarro.setText("Cadastrar Carro");
        BtSalvarCarro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtSalvarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarCarroActionPerformed(evt);
            }
        });

        LbPlacaCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbPlacaCadastro.setText("Placa:");

        LbAnoCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbAnoCadastro.setText("Ano:");

        InternaResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        InternaResultado.setVisible(true);

        LbModeloResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbModeloResultado.setText("Modelo:");

        LbAnoResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbAnoResultado.setText("Ano:");

        LbMarcaResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbMarcaResultado.setText("Marca:");

        LbPlacaResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbPlacaResultado.setText("Placa:");

        LbNomeResultado5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado5.setText("Cadastrado em:");

        BarraProgresso.setForeground(new java.awt.Color(255, 0, 51));
        BarraProgresso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROGRESSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        BarraProgresso.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("RESULTADO:");

        LbPlacaResultado1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbPlacaResultado1.setText("Cor:");

        LbIdResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbIdResultado.setText("ID:");

        javax.swing.GroupLayout InternaResultadoLayout = new javax.swing.GroupLayout(InternaResultado.getContentPane());
        InternaResultado.getContentPane().setLayout(InternaResultadoLayout);
        InternaResultadoLayout.setHorizontalGroup(
            InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InternaResultadoLayout.createSequentialGroup()
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaResultadoLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel3))
                    .addGroup(InternaResultadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbPlacaResultado1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternaResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InternaResultadoLayout.createSequentialGroup()
                        .addComponent(LbModeloResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoModeloResultado))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InternaResultadoLayout.createSequentialGroup()
                        .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InternaResultadoLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(LbIdResultado)
                                .addGap(18, 18, 18)
                                .addComponent(CampoIdResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(InternaResultadoLayout.createSequentialGroup()
                                    .addComponent(LbMarcaResultado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CampoMarcaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(InternaResultadoLayout.createSequentialGroup()
                                    .addComponent(LbAnoResultado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CampoAnoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternaResultadoLayout.createSequentialGroup()
                                    .addComponent(LbNomeResultado5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CampoResultadoCadastro))
                                .addGroup(InternaResultadoLayout.createSequentialGroup()
                                    .addComponent(LbPlacaResultado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CampoResultadoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CampoResultadoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        InternaResultadoLayout.setVerticalGroup(
            InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaResultadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbIdResultado)
                    .addComponent(CampoIdResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbModeloResultado)
                    .addComponent(CampoModeloResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbMarcaResultado)
                    .addComponent(CampoMarcaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAnoResultado)
                    .addComponent(CampoAnoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPlacaResultado)
                    .addComponent(CampoResultadoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPlacaResultado1)
                    .addComponent(CampoResultadoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoResultadoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNomeResultado5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BarraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        LbCadastrarCor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbCadastrarCor.setText("Cor:");

        IconeInformativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/em-formacao.png"))); // NOI18N
        IconeInformativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconeInformativoMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InternaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(BtSalvarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbPlacaCadastro)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LbCadastrarCor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoCorCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoPlacaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IconeInformativo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbAnoCadastro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbMarcaCadastro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbModeloCadastro, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoAnoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                    .addComponent(CampoMarcaCadastro)
                                    .addComponent(CampoModeloCadastro))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InternaEditarUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconeInformativo)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoModeloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbModeloCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoMarcaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbMarcaCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoAnoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbAnoCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoPlacaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbPlacaCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbCadastrarCor)
                            .addComponent(CampoCorCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(BtSalvarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InternaResultado))
                    .addComponent(InternaEditarUsuario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoMarcaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoMarcaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoMarcaCadastroActionPerformed

    private void BtSalvarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSalvarCarroActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        // 
    }//GEN-LAST:event_BtEditarActionPerformed

    private void CampoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisarActionPerformed

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        int linha = TabelaClientes.getSelectedRow();
        if (linha == -1) {
            return;
        }
    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void CampoInfoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInfoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInfoPlacaActionPerformed

    private void CampoInfoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInfoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInfoAnoActionPerformed

    private void IconeInformativoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeInformativoMouseEntered
        JOptionPane.showMessageDialog(null,
                "Selecione um Cliente Antes de Cadastrar um carro",
                "Aviso",
                JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_IconeInformativoMouseEntered

    public String GetIdcarro() {
        return CampoInfoId.getText();
    }

    public String GetModelo() {
        return CampoModeloCadastro.getText();
    }

    public String GetPlaca() {
        return CampoPlacaCadastro.getText();
    }

    public String GetMarca() {
        return CampoMarcaCadastro.getText();
    }

    public String GetAnoCarro() {
        return CampoAnoCadastro.getText();
    }

    public String GetCor() {
        return CampoCorCadastrar.getText();
    }

    public Map<String, String> InfoUsuarioEditar() {
        Map<String, String> dados = new HashMap<>();
        dados.put("id", CampoInfoId.getText());
        dados.put("modelo", CampoInfoModelo.getText());
        dados.put("marca", CampoInfoMarca.getText());
        dados.put("placa", CampoInfoPlaca.getText());
        dados.put("cor", CampoInfoCor.getText());
        dados.put("ano", CampoInfoAno.getText());
        dados.put("dataCadastro", CampoInfoDataCadastro.getText());
        dados.put("dataAtualizacao", CampoInfoDataAtualizacao.getText());
        return dados;
    }

    public javax.swing.JButton getBtSalvar() {
        return BtSalvarCarro;
    }

    public javax.swing.JButton getBtExlcuir() {
        return BtExcluir;
    }

    public javax.swing.JButton getBtEditar() {
        return BtEditar;
    }

    public JProgressBar AtivarBarraProgresso() {
        return BarraProgresso;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgresso;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtSalvarCarro;
    private javax.swing.JTextField CampoAnoCadastro;
    private javax.swing.JTextField CampoAnoResultado;
    private javax.swing.JTextField CampoCorCadastrar;
    private javax.swing.JTextField CampoIdResultado;
    private javax.swing.JTextField CampoInfoAno;
    private javax.swing.JTextField CampoInfoCor;
    private javax.swing.JTextField CampoInfoDataAtualizacao;
    private javax.swing.JTextField CampoInfoDataCadastro;
    private javax.swing.JTextField CampoInfoId;
    private javax.swing.JTextField CampoInfoMarca;
    private javax.swing.JTextField CampoInfoModelo;
    private javax.swing.JTextField CampoInfoPlaca;
    private javax.swing.JTextField CampoMarcaCadastro;
    private javax.swing.JTextField CampoMarcaResultado;
    private javax.swing.JTextField CampoModeloCadastro;
    private javax.swing.JTextField CampoModeloResultado;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JTextField CampoPlacaCadastro;
    private javax.swing.JTextField CampoResultadoCadastro;
    private javax.swing.JTextField CampoResultadoCor;
    private javax.swing.JTextField CampoResultadoPlaca;
    private javax.swing.JLabel IconPesquisar;
    private javax.swing.JLabel IconeInformativo;
    private javax.swing.JInternalFrame InternaDadosPesquisa;
    private javax.swing.JInternalFrame InternaEditarUsuario;
    private javax.swing.JInternalFrame InternaResultado;
    private javax.swing.JLabel LbAnoCadastro;
    private javax.swing.JLabel LbAnoResultado;
    private javax.swing.JLabel LbCadastrarCor;
    private javax.swing.JLabel LbIdResultado;
    private javax.swing.JLabel LbInfoAno;
    private javax.swing.JLabel LbInfoCPF;
    private javax.swing.JLabel LbInfoDataAtualizacao;
    private javax.swing.JLabel LbInfoDataCadastro;
    private javax.swing.JLabel LbInfoMarca;
    private javax.swing.JLabel LbInfoModelo;
    private javax.swing.JLabel LbInfoNome2;
    private javax.swing.JLabel LbMarcaCadastro;
    private javax.swing.JLabel LbMarcaResultado;
    private javax.swing.JLabel LbModeloCadastro;
    private javax.swing.JLabel LbModeloResultado;
    private javax.swing.JLabel LbNomeResultado5;
    private javax.swing.JLabel LbPlacaCadastro;
    private javax.swing.JLabel LbPlacaResultado;
    private javax.swing.JLabel LbPlacaResultado1;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoPesquisar() {
        return CampoPesquisar;
    }

    public JTable getTabelaUsuarios() {
        return TabelaClientes;
    }

    public void RetornoDados(String id, String Modelo, String Marca, String Placa, String Cor, String Ano, String DataCadastro) {

        CampoIdResultado.setText(id);
        CampoModeloResultado.setText(Modelo);
        CampoMarcaResultado.setText(Marca);
        CampoAnoResultado.setText(Ano);
        CampoResultadoPlaca.setText(Placa);
        CampoResultadoCadastro.setText(DataCadastro);
    }

    public void InfoUsuario(String id, String nome, String email, String cpf, String telefone, String Endereco, String dataCadastro, String dataAtualizacao) {
        this.CampoInfoId.setText(id);

        this.CampoInfoModelo.setText(email);
        this.CampoInfoCor.setText(telefone);
        this.CampoInfoPlaca.setText(cpf);
        this.CampoInfoAno.setText(Endereco);
        this.CampoInfoDataCadastro.setText(dataCadastro);
        this.CampoInfoDataAtualizacao.setText(dataAtualizacao);
    }
}
