/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oficina.project.view.TelaPrincipal.CarrosView;

import com.oficina.project.controller.Carros.BuscarClienteVincularCarroController;
import com.oficina.project.controller.Clientes.BuscarClienteController;
import com.oficina.project.view.TelaPrincipal.TelaPrincipal;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Venicio
 */
public class TelaVincularClienteCarros extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVincularClienteCarros.class.getName());

    /**
     * Creates new form TelaVincularClienteCarros
     */
    private TelaPrincipal telaPrincipal; // referência da tela principal

    public TelaVincularClienteCarros() {
        initComponents();
        new com.oficina.project.controller.Carros.BuscarClienteVincularCarroController(this);
    }

    public TelaVincularClienteCarros(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal; // guarda a instância recebida
        initComponents();
        new com.oficina.project.controller.Carros.BuscarClienteVincularCarroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoPesquisarCliente = new javax.swing.JTextField();
        IconePesquisar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaVincularCliente = new javax.swing.JTable();
        LbClienteSelecionado = new javax.swing.JLabel();
        CampoNomeClienteSelecionado = new javax.swing.JTextField();
        LbID = new javax.swing.JLabel();
        CampoIdSelecionado = new javax.swing.JTextField();
        BotaoVincular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        IconePesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N

        TabelaVincularCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID:", "NOME:"
            }
        ));
        TabelaVincularCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaVincularClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaVincularCliente);

        LbClienteSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LbClienteSelecionado.setText("CLIENTE SELECIONADO:");

        LbID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LbID.setText("ID:");

        BotaoVincular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoVincular.setText("VINCULAR");
        BotaoVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVincularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(IconePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoPesquisarCliente))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(LbClienteSelecionado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoNomeClienteSelecionado)
                            .addGap(18, 18, 18)
                            .addComponent(LbID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoIdSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(BotaoVincular)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconePesquisar)
                    .addComponent(CampoPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbClienteSelecionado)
                    .addComponent(CampoNomeClienteSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbID)
                    .addComponent(CampoIdSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoVincular)
                .addGap(282, 282, 282))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaVincularClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaVincularClienteMouseClicked
        int linha = TabelaVincularCliente.getSelectedRow();
        if (linha == -1) {
            return;
        }
        new BuscarClienteVincularCarroController(this).ClienteSelecionado(linha);
    }//GEN-LAST:event_TabelaVincularClienteMouseClicked

    private void BotaoVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVincularActionPerformed
        telaPrincipal.SetIdClienteCarro(CampoIdSelecionado.getText());
        telaPrincipal.SetNomeClienteCarroVinculado(CampoNomeClienteSelecionado.getText());// usa a instância correta
        JOptionPane.showMessageDialog(null, "Cliente Vinculado Com Sucesso");
        this.dispose();

    }//GEN-LAST:event_BotaoVincularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVincularClienteCarros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoVincular;
    private javax.swing.JTextField CampoIdSelecionado;
    private javax.swing.JTextField CampoNomeClienteSelecionado;
    private javax.swing.JTextField CampoPesquisarCliente;
    private javax.swing.JLabel IconePesquisar;
    private javax.swing.JLabel LbClienteSelecionado;
    private javax.swing.JLabel LbID;
    private javax.swing.JTable TabelaVincularCliente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public JTextField getCampoPesquisarVincularCliente() {
        return CampoPesquisarCliente;
    }

    public JTable getTabelaVincularClientes() {
        return TabelaVincularCliente;
    }

    public void setClienteSelecionado(String id, String nome) {
        CampoNomeClienteSelecionado.setText(nome);
        CampoIdSelecionado.setText(id);
    }
}
