/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oficina.project.view.TelaPrincipal;

import com.oficina.project.controller.Administradores.BuscarAdmController;
import com.oficina.project.controller.Administradores.CadastrarAdmController;
import com.oficina.project.controller.Clientes.BuscarClienteController;
import com.oficina.project.view.TelaPrincipal.AdmViews.CadastrarAdmView;
import com.oficina.project.view.TelaPrincipal.CarrosView.CadastrarCarrosView;
import com.oficina.project.view.TelaPrincipal.ClienteViews.CadastrarClienteView;
import com.oficina.project.view.TelaPrincipal.MenuServicosView.MenuServicosView;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Venicio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        new com.oficina.project.controller.Clientes.BuscarClienteController(this);
        new com.oficina.project.controller.Clientes.CadastrarClienteController(this);
        new com.oficina.project.controller.Clientes.EditarClienteController(this);
   
        addComponentListener(new java.awt.event.ComponentAdapter() {
    @Override
    public void componentResized(java.awt.event.ComponentEvent evt) {
        // Redimensiona o JLabel
        LOGO.setSize(TelaInterna.getSize());

        // Redimensiona o ícone da imagem
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/icones/LogoOficina.png"));
        Image scaledImage = originalIcon.getImage().getScaledInstance(
            TelaInterna.getWidth(),
            TelaInterna.getHeight(),
            Image.SCALE_SMOOTH
        );
        LOGO.setIcon(new ImageIcon(scaledImage));
    }
});



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        TelaInterna = new javax.swing.JDesktopPane();
        InternaCliente = new javax.swing.JInternalFrame();
        BtSalvarCliente = new javax.swing.JButton();
        CampoNomeCadastroCliente = new javax.swing.JTextField();
        LbCpfCadastro = new javax.swing.JLabel();
        CampoTelefoneCadastroCliente = new javax.swing.JTextField();
        LbEnderecoCadastro = new javax.swing.JLabel();
        CampoEmailCadastroCliente = new javax.swing.JTextField();
        LbNomeCadastro = new javax.swing.JLabel();
        LbEmailCadastro = new javax.swing.JLabel();
        CampoCpfCadastroCliente = new javax.swing.JTextField();
        CampoEnderecoCliente = new javax.swing.JTextField();
        InternaResultado = new javax.swing.JInternalFrame();
        LbNomeResultado = new javax.swing.JLabel();
        LbNomeResultado1 = new javax.swing.JLabel();
        LbNomeResultado2 = new javax.swing.JLabel();
        LbNomeResultado3 = new javax.swing.JLabel();
        LbNomeResultado4 = new javax.swing.JLabel();
        LbNomeResultado5 = new javax.swing.JLabel();
        CampoNomeResultadoCliente = new javax.swing.JTextField();
        CampoEnderecoResultadoCliente = new javax.swing.JTextField();
        CampoEmailResultadoCliente = new javax.swing.JTextField();
        CampoTelefoneResultadoCliente = new javax.swing.JTextField();
        CampoResultadoCadastroCliente = new javax.swing.JTextField();
        CampoResultadoCpfCliente = new javax.swing.JTextField();
        BarraProgressoCliente = new javax.swing.JProgressBar();
        LbResultaadoBarraCliente = new javax.swing.JLabel();
        LbTelefoneCadastro = new javax.swing.JLabel();
        InternaEditarUsuario = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        CampoPesquisar = new javax.swing.JTextField();
        InternaDadosPesquisa = new javax.swing.JInternalFrame();
        LbInfoEmail = new javax.swing.JLabel();
        LbInfoNome1 = new javax.swing.JLabel();
        LbInfotelefone = new javax.swing.JLabel();
        LbInfoDataCadastro = new javax.swing.JLabel();
        LbInfoDataAtualizacao = new javax.swing.JLabel();
        CampoInfoDataAtualizacao = new javax.swing.JTextField();
        CampoInfoDataCadastro = new javax.swing.JTextField();
        CampoInfoNome = new javax.swing.JTextField();
        CampoInfoEmail = new javax.swing.JTextField();
        CampoInfoTelefone = new javax.swing.JTextField();
        LbInfoNome2 = new javax.swing.JLabel();
        CampoInfoId = new javax.swing.JTextField();
        LbInfoEndereço = new javax.swing.JLabel();
        LbInfoCPF = new javax.swing.JLabel();
        CampoInfoEndereco = new javax.swing.JTextField();
        CampoInfoCPF = new javax.swing.JTextField();
        BtEditar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        IconPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuServicos = new javax.swing.JMenu();
        MenuUsuarios = new javax.swing.JMenu();
        MenuFuncionarioAction = new javax.swing.JMenuItem();
        MenuClienteAction = new javax.swing.JMenuItem();
        MenuCarros = new javax.swing.JMenuItem();
        JMenuRelatorios = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        TelaInterna.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        InternaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        InternaCliente.setClosable(true);
        InternaCliente.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        InternaCliente.setIconifiable(true);
        InternaCliente.setMaximizable(true);
        InternaCliente.setResizable(true);
        InternaCliente.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ICONECLIENTE.png"))); // NOI18N
        try {
            InternaCliente.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        InternaCliente.setVisible(false);

        BtSalvarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtSalvarCliente.setText("Cadastrar Usuario");
        BtSalvarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarClienteActionPerformed(evt);
            }
        });

        LbCpfCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbCpfCadastro.setText("CPF:");

        CampoTelefoneCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneCadastroClienteActionPerformed(evt);
            }
        });

        LbEnderecoCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbEnderecoCadastro.setText("Endereço:");

        LbNomeCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbNomeCadastro.setText("Nome:");

        LbEmailCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbEmailCadastro.setText("Email:");

        InternaResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        InternaResultado.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ICONECLIENTE.png"))); // NOI18N
        InternaResultado.setVisible(true);

        LbNomeResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado.setText("Nome:");

        LbNomeResultado1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado1.setText("Email:");

        LbNomeResultado2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado2.setText("Endereço:");

        LbNomeResultado3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado3.setText("Telefone:");

        LbNomeResultado4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado4.setText("CPF:");

        LbNomeResultado5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado5.setText("Cadastrado em:");

        BarraProgressoCliente.setForeground(new java.awt.Color(255, 0, 51));
        BarraProgressoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROGRESSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        BarraProgressoCliente.setName(""); // NOI18N

        LbResultaadoBarraCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LbResultaadoBarraCliente.setText("RESULTADO:");

        javax.swing.GroupLayout InternaResultadoLayout = new javax.swing.GroupLayout(InternaResultado.getContentPane());
        InternaResultado.getContentPane().setLayout(InternaResultadoLayout);
        InternaResultadoLayout.setHorizontalGroup(
            InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaResultadoLayout.createSequentialGroup()
                        .addComponent(LbNomeResultado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoEmailResultadoCliente))
                    .addGroup(InternaResultadoLayout.createSequentialGroup()
                        .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addComponent(LbNomeResultado5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoResultadoCadastroCliente))
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addComponent(LbNomeResultado3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoTelefoneResultadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addComponent(LbNomeResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNomeResultadoCliente))
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbNomeResultado2)
                                    .addComponent(LbNomeResultado4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoEnderecoResultadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CampoResultadoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
            .addGroup(InternaResultadoLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(LbResultaadoBarraCliente)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(BarraProgressoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InternaResultadoLayout.setVerticalGroup(
            InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaResultadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado)
                    .addComponent(CampoNomeResultadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado1)
                    .addComponent(CampoEmailResultadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado3)
                    .addComponent(CampoTelefoneResultadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado2)
                    .addComponent(CampoEnderecoResultadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado4)
                    .addComponent(CampoResultadoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado5)
                    .addComponent(CampoResultadoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(LbResultaadoBarraCliente)
                .addGap(32, 32, 32)
                .addComponent(BarraProgressoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        LbTelefoneCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbTelefoneCadastro.setText("Telefone:");

        InternaEditarUsuario.setBackground(new java.awt.Color(183, 183, 167));
        InternaEditarUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDITAR INFORMAÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14))); // NOI18N
        InternaEditarUsuario.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ICONECLIENTE.png"))); // NOI18N
        InternaEditarUsuario.setVisible(true);

        TabelaClientes.setBackground(new java.awt.Color(204, 204, 204));
        TabelaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelaClientes.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Email", "CPF", "Telefone", "Endereco", "Data de Cadastro", "Data de Atualização"
            }
        ));
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);

        CampoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisarActionPerformed(evt);
            }
        });

        InternaDadosPesquisa.setBackground(new java.awt.Color(153, 153, 153));
        InternaDadosPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informações de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        InternaDadosPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        InternaDadosPesquisa.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/usuario.png"))); // NOI18N
        InternaDadosPesquisa.setVisible(true);

        LbInfoEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoEmail.setText("Email:");

        LbInfoNome1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoNome1.setText("Nome:");

        LbInfotelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfotelefone.setText("Telefone:");

        LbInfoDataCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoDataCadastro.setText("Data de Cadastro:");

        LbInfoDataAtualizacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoDataAtualizacao.setText("Data de Atualização:");

        LbInfoNome2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoNome2.setText("ID:");

        LbInfoEndereço.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoEndereço.setText("Endereço:");

        LbInfoCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoCPF.setText("CPF:");

        CampoInfoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInfoCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InternaDadosPesquisaLayout = new javax.swing.GroupLayout(InternaDadosPesquisa.getContentPane());
        InternaDadosPesquisa.getContentPane().setLayout(InternaDadosPesquisaLayout);
        InternaDadosPesquisaLayout.setHorizontalGroup(
            InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbInfoNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoInfoNome)
                                    .addComponent(CampoInfoEmail)))
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addComponent(LbInfotelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoInfoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbInfoNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396))
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbInfoDataAtualizacao)
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(LbInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoInfoDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbInfoCPF)
                            .addComponent(LbInfoEndereço))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoInfoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoInfoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        InternaDadosPesquisaLayout.setVerticalGroup(
            InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoNome1)
                    .addComponent(CampoInfoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbInfoNome2)
                    .addComponent(CampoInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoEmail)
                    .addComponent(CampoInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoInfoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbInfotelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoEndereço)
                    .addComponent(CampoInfoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoCPF)
                    .addComponent(CampoInfoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoDataCadastro)
                    .addComponent(CampoInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoDataAtualizacao)
                    .addComponent(CampoInfoDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        IconPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Editar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Excluir");

        javax.swing.GroupLayout InternaEditarUsuarioLayout = new javax.swing.GroupLayout(InternaEditarUsuario.getContentPane());
        InternaEditarUsuario.getContentPane().setLayout(InternaEditarUsuarioLayout);
        InternaEditarUsuarioLayout.setHorizontalGroup(
            InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel1)
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel2))
                                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(BtEditar)
                                        .addGap(48, 48, 48)
                                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(143, 143, 143))
                            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                .addComponent(IconPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(InternaDadosPesquisa)))
                .addContainerGap())
        );
        InternaEditarUsuarioLayout.setVerticalGroup(
            InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconPesquisar))
                        .addGap(26, 26, 26)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtEditar)
                            .addComponent(BtExcluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InternaDadosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout InternaClienteLayout = new javax.swing.GroupLayout(InternaCliente.getContentPane());
        InternaCliente.getContentPane().setLayout(InternaClienteLayout);
        InternaClienteLayout.setHorizontalGroup(
            InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaClienteLayout.createSequentialGroup()
                .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaClienteLayout.createSequentialGroup()
                        .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternaClienteLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbEmailCadastro)
                                    .addComponent(LbNomeCadastro)))
                            .addGroup(InternaClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LbTelefoneCadastro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternaClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LbEnderecoCadastro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoEnderecoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(CampoTelefoneCadastroCliente)
                            .addComponent(CampoEmailCadastroCliente)
                            .addComponent(CampoNomeCadastroCliente)))
                    .addGroup(InternaClienteLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(LbCpfCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoCpfCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InternaClienteLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(BtSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InternaClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InternaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InternaEditarUsuario)
                .addContainerGap())
        );
        InternaClienteLayout.setVerticalGroup(
            InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaClienteLayout.createSequentialGroup()
                .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaClienteLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbNomeCadastro)
                            .addComponent(CampoNomeCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbEmailCadastro)
                            .addComponent(CampoEmailCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoTelefoneCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbTelefoneCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbEnderecoCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoCpfCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbCpfCadastro))
                        .addGap(18, 18, 18)
                        .addComponent(BtSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InternaResultado))
                    .addComponent(InternaEditarUsuario))
                .addContainerGap())
        );

        TelaInterna.add(InternaCliente);
        InternaCliente.setBounds(10, 10, 1500, 810);

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/LogoOficina.png"))); // NOI18N
        TelaInterna.add(LOGO);
        LOGO.setBounds(-3, -4, 1530, 840);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        MenuServicos.setText("Serviços");
        MenuServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuServicosMouseClicked(evt);
            }
        });
        MenuServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuServicosActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuServicos);

        MenuUsuarios.setText("Usuários");
        MenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuariosActionPerformed(evt);
            }
        });

        MenuFuncionarioAction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuFuncionarioAction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuFuncionarioAction.setText("Cadastrar/Editar Funcionarios");
        MenuFuncionarioAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFuncionarioActionActionPerformed(evt);
            }
        });
        MenuUsuarios.add(MenuFuncionarioAction);

        MenuClienteAction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuClienteAction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuClienteAction.setText("Cadastrar/Editar Clientes");
        MenuClienteAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClienteActionActionPerformed(evt);
            }
        });
        MenuUsuarios.add(MenuClienteAction);

        MenuCarros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuCarros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuCarros.setText("Cadastrar/Editar Carro");
        MenuCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCarrosActionPerformed(evt);
            }
        });
        MenuUsuarios.add(MenuCarros);

        jMenuBar1.add(MenuUsuarios);

        JMenuRelatorios.setText("Relatorios");
        jMenuBar1.add(JMenuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaInterna, javax.swing.GroupLayout.DEFAULT_SIZE, 1520, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaInterna, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuFuncionarioActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFuncionarioActionActionPerformed
        CadastrarAdmView iniciar = new CadastrarAdmView();
        iniciar.setVisible(true);
        iniciar.toFront();
        TelaInterna.add(iniciar);


    }//GEN-LAST:event_MenuFuncionarioActionActionPerformed

    private void MenuClienteActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClienteActionActionPerformed
        InternaCliente.setVisible(true);
        

    }//GEN-LAST:event_MenuClienteActionActionPerformed

    private void MenuServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuServicosActionPerformed
        MenuServicosView iniciar = new MenuServicosView();
        iniciar.setVisible(true);
        TelaInterna.add(iniciar);

    }//GEN-LAST:event_MenuServicosActionPerformed

    private void MenuServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuServicosMouseClicked
        MenuServicosView iniciar = new MenuServicosView();
        iniciar.setVisible(true);
        TelaInterna.add(iniciar);

    }//GEN-LAST:event_MenuServicosMouseClicked

    private void MenuCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCarrosActionPerformed
        CadastrarCarrosView iniciar = new CadastrarCarrosView();
        iniciar.setVisible(true);
        TelaInterna.add(iniciar);

    }//GEN-LAST:event_MenuCarrosActionPerformed

    private void MenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuariosActionPerformed
        // TODO 
    }//GEN-LAST:event_MenuUsuariosActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        //
    }//GEN-LAST:event_BtEditarActionPerformed

    private void CampoInfoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInfoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInfoCPFActionPerformed

    private void CampoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisarActionPerformed

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        int linha = TabelaClientes.getSelectedRow();
        if (linha == -1) {
            return;
        }
        new BuscarClienteController(this).ClienteSelecionado(linha);
    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void CampoTelefoneCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneCadastroClienteActionPerformed

    private void BtSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSalvarClienteActionPerformed
    public String GetIdUsuario() {
        return CampoInfoId.getText();
    }

    public String GetNome() {
        return CampoNomeCadastroCliente.getText();
    }

    public String GetEmail() {
        return CampoEmailCadastroCliente.getText();
    }

    public String GetCpf() {
        return CampoCpfCadastroCliente.getText();
    }

    public String GetTelefone() {
        return CampoTelefoneCadastroCliente.getText();
    }

    public String GetEndereco() {
        return CampoEnderecoCliente.getText();
    }

    public Map<String, String> InfoUsuarioEditar() {
        Map<String, String> dados = new HashMap<>();
        dados.put("id", CampoInfoId.getText());
        dados.put("Nome", CampoInfoNome.getText());
        dados.put("email", CampoInfoEmail.getText());
        dados.put("cpf", CampoInfoCPF.getText());
        dados.put("telefone", CampoInfoTelefone.getText());
        dados.put("endereco", CampoInfoEndereco.getText());
        dados.put("dataCadastro", CampoInfoDataCadastro.getText());
        dados.put("dataAtualizacao", CampoInfoDataAtualizacao.getText());
        return dados;
    }

    public javax.swing.JButton getBtSalvar() {
        return BtSalvarCliente;
    }

    public javax.swing.JButton getBtExlcuir() {
        return BtExcluir;
    }

    public javax.swing.JButton getBtEditar() {
        return BtEditar;
    }

    public JProgressBar AtivarBarraProgresso() {
        return BarraProgressoCliente;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgressoCliente;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtSalvarCliente;
    private javax.swing.JTextField CampoCpfCadastroCliente;
    private javax.swing.JTextField CampoEmailCadastroCliente;
    private javax.swing.JTextField CampoEmailResultadoCliente;
    private javax.swing.JTextField CampoEnderecoCliente;
    private javax.swing.JTextField CampoEnderecoResultadoCliente;
    private javax.swing.JTextField CampoInfoCPF;
    private javax.swing.JTextField CampoInfoDataAtualizacao;
    private javax.swing.JTextField CampoInfoDataCadastro;
    private javax.swing.JTextField CampoInfoEmail;
    private javax.swing.JTextField CampoInfoEndereco;
    private javax.swing.JTextField CampoInfoId;
    private javax.swing.JTextField CampoInfoNome;
    private javax.swing.JTextField CampoInfoTelefone;
    private javax.swing.JTextField CampoNomeCadastroCliente;
    private javax.swing.JTextField CampoNomeResultadoCliente;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JTextField CampoResultadoCadastroCliente;
    private javax.swing.JTextField CampoResultadoCpfCliente;
    private javax.swing.JTextField CampoTelefoneCadastroCliente;
    private javax.swing.JTextField CampoTelefoneResultadoCliente;
    private javax.swing.JLabel IconPesquisar;
    private javax.swing.JInternalFrame InternaCliente;
    private javax.swing.JInternalFrame InternaDadosPesquisa;
    private javax.swing.JInternalFrame InternaEditarUsuario;
    private javax.swing.JInternalFrame InternaResultado;
    private javax.swing.JMenu JMenuRelatorios;
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel LbCpfCadastro;
    private javax.swing.JLabel LbEmailCadastro;
    private javax.swing.JLabel LbEnderecoCadastro;
    private javax.swing.JLabel LbInfoCPF;
    private javax.swing.JLabel LbInfoDataAtualizacao;
    private javax.swing.JLabel LbInfoDataCadastro;
    private javax.swing.JLabel LbInfoEmail;
    private javax.swing.JLabel LbInfoEndereço;
    private javax.swing.JLabel LbInfoNome1;
    private javax.swing.JLabel LbInfoNome2;
    private javax.swing.JLabel LbInfotelefone;
    private javax.swing.JLabel LbNomeCadastro;
    private javax.swing.JLabel LbNomeResultado;
    private javax.swing.JLabel LbNomeResultado1;
    private javax.swing.JLabel LbNomeResultado2;
    private javax.swing.JLabel LbNomeResultado3;
    private javax.swing.JLabel LbNomeResultado4;
    private javax.swing.JLabel LbNomeResultado5;
    private javax.swing.JLabel LbResultaadoBarraCliente;
    private javax.swing.JLabel LbTelefoneCadastro;
    private javax.swing.JMenuItem MenuCarros;
    private javax.swing.JMenuItem MenuClienteAction;
    private javax.swing.JMenuItem MenuFuncionarioAction;
    private javax.swing.JMenu MenuServicos;
    public static javax.swing.JMenu MenuUsuarios;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JDesktopPane TelaInterna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
  public JTextField getCampoPesquisar() {
        return CampoPesquisar;
    }

    public JTable getTabelaUsuarios() {
        return TabelaClientes;
    }

    public void RetornoDados(String Nome, String Email, String Telefone, String Endereco, String Cpf, String DataCadastro) {
        CampoNomeResultadoCliente.setText(Nome);
        CampoEmailResultadoCliente.setText(Email);
        CampoTelefoneResultadoCliente.setText(Telefone);
        CampoEnderecoResultadoCliente.setText(Endereco);
        CampoResultadoCpfCliente.setText(Cpf);
        CampoResultadoCadastroCliente.setText(DataCadastro);
    }

    public void InfoUsuario(String id, String nome, String email, String cpf, String telefone, String Endereco, String dataCadastro, String dataAtualizacao) {
        this.CampoInfoId.setText(id);
        this.CampoInfoNome.setText(nome);
        this.CampoInfoEmail.setText(email);
        this.CampoInfoTelefone.setText(telefone);
        this.CampoInfoCPF.setText(cpf);
        this.CampoInfoEndereco.setText(Endereco);
        this.CampoInfoDataCadastro.setText(dataCadastro);
        this.CampoInfoDataAtualizacao.setText(dataAtualizacao);
    }
}
