/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.oficina.project.view.TelaPrincipal.ClienteViews;

import com.oficina.project.controller.Clientes.BuscarClienteController;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ComboBoxEditor;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Venicio
 */
public class CadastrarClienteView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarAdmView
     */
    public CadastrarClienteView() {
        initComponents();
        //TODO SEM USO
              

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        CampoNomeCadastro = new javax.swing.JTextField();
        CampoTelefoneCadastro = new javax.swing.JTextField();
        CampoEmailCadastro = new javax.swing.JTextField();
        LbNomeCadastro = new javax.swing.JLabel();
        LbEmailCadastro = new javax.swing.JLabel();
        LbTelefoneCadastro = new javax.swing.JLabel();
        InternaEditarUsuario = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        CampoPesquisar = new javax.swing.JTextField();
        InternaDadosPesquisa = new javax.swing.JInternalFrame();
        LbInfoEmail = new javax.swing.JLabel();
        LbInfoNome1 = new javax.swing.JLabel();
        LbInfotelefone = new javax.swing.JLabel();
        LbInfoDataCadastro = new javax.swing.JLabel();
        LbInfoDataAtualizacao = new javax.swing.JLabel();
        CampoInfoDataAtualizacao = new javax.swing.JTextField();
        CampoInfoDataCadastro = new javax.swing.JTextField();
        CampoInfoNome = new javax.swing.JTextField();
        CampoInfoEmail = new javax.swing.JTextField();
        CampoInfoTelefone = new javax.swing.JTextField();
        LbInfoNome2 = new javax.swing.JLabel();
        CampoInfoId = new javax.swing.JTextField();
        LbInfoEndereço = new javax.swing.JLabel();
        LbInfoCPF = new javax.swing.JLabel();
        CampoInfoEndereco = new javax.swing.JTextField();
        CampoInfoCPF = new javax.swing.JTextField();
        BtEditar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        IconPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtSalvar = new javax.swing.JButton();
        LbCpfCadastro = new javax.swing.JLabel();
        LbEnderecoCadastro = new javax.swing.JLabel();
        CampoCpfCadastro = new javax.swing.JTextField();
        CampoEndereco = new javax.swing.JTextField();
        InternaResultado = new javax.swing.JInternalFrame();
        LbNomeResultado = new javax.swing.JLabel();
        LbNomeResultado1 = new javax.swing.JLabel();
        LbNomeResultado2 = new javax.swing.JLabel();
        LbNomeResultado3 = new javax.swing.JLabel();
        LbNomeResultado4 = new javax.swing.JLabel();
        LbNomeResultado5 = new javax.swing.JLabel();
        CampoNomeResultado = new javax.swing.JTextField();
        CampoEnderecoResultado = new javax.swing.JTextField();
        CampoEmailResultado = new javax.swing.JTextField();
        CampoTelefoneResultado = new javax.swing.JTextField();
        CampoResultadoCadastro = new javax.swing.JTextField();
        CampoResultadoCpf = new javax.swing.JTextField();
        BarraProgresso = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "    Cadastrar Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        CampoTelefoneCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneCadastroActionPerformed(evt);
            }
        });

        LbNomeCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbNomeCadastro.setText("Nome:");

        LbEmailCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbEmailCadastro.setText("Email:");

        LbTelefoneCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbTelefoneCadastro.setText("Telefone:");

        InternaEditarUsuario.setBackground(new java.awt.Color(183, 183, 167));
        InternaEditarUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14))); // NOI18N
        InternaEditarUsuario.setVisible(true);

        TabelaClientes.setBackground(new java.awt.Color(204, 204, 204));
        TabelaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelaClientes.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Email", "CPF", "Telefone", "Endereco", "Data de Cadastro", "Data de Atualização"
            }
        ));
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);

        CampoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisarActionPerformed(evt);
            }
        });

        InternaDadosPesquisa.setBackground(new java.awt.Color(153, 153, 153));
        InternaDadosPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informações de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        InternaDadosPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        InternaDadosPesquisa.setVisible(true);

        LbInfoEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoEmail.setText("Email:");

        LbInfoNome1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoNome1.setText("Nome:");

        LbInfotelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfotelefone.setText("Telefone:");

        LbInfoDataCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoDataCadastro.setText("Data de Cadastro:");

        LbInfoDataAtualizacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoDataAtualizacao.setText("Data de Atualização:");

        LbInfoNome2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoNome2.setText("ID:");

        LbInfoEndereço.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoEndereço.setText("Endereço:");

        LbInfoCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoCPF.setText("CPF:");

        CampoInfoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInfoCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InternaDadosPesquisaLayout = new javax.swing.GroupLayout(InternaDadosPesquisa.getContentPane());
        InternaDadosPesquisa.getContentPane().setLayout(InternaDadosPesquisaLayout);
        InternaDadosPesquisaLayout.setHorizontalGroup(
            InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbInfoNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoInfoNome)
                                    .addComponent(CampoInfoEmail)))
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addComponent(LbInfotelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoInfoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbInfoNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396))
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbInfoDataAtualizacao)
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(LbInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoInfoDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbInfoCPF)
                            .addComponent(LbInfoEndereço))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoInfoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoInfoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        InternaDadosPesquisaLayout.setVerticalGroup(
            InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoNome1)
                    .addComponent(CampoInfoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbInfoNome2)
                    .addComponent(CampoInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoEmail)
                    .addComponent(CampoInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoInfoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbInfotelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoEndereço)
                    .addComponent(CampoInfoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoCPF)
                    .addComponent(CampoInfoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoDataCadastro)
                    .addComponent(CampoInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoDataAtualizacao)
                    .addComponent(CampoInfoDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        IconPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Editar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Excluir");

        javax.swing.GroupLayout InternaEditarUsuarioLayout = new javax.swing.GroupLayout(InternaEditarUsuario.getContentPane());
        InternaEditarUsuario.getContentPane().setLayout(InternaEditarUsuarioLayout);
        InternaEditarUsuarioLayout.setHorizontalGroup(
            InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel1)
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel2))
                                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(BtEditar)
                                        .addGap(48, 48, 48)
                                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(143, 143, 143))
                            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                .addComponent(IconPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(InternaDadosPesquisa)))
                .addContainerGap())
        );
        InternaEditarUsuarioLayout.setVerticalGroup(
            InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconPesquisar))
                        .addGap(26, 26, 26)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtEditar)
                            .addComponent(BtExcluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InternaDadosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtSalvar.setText("Cadastrar Usuario");
        BtSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        LbCpfCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbCpfCadastro.setText("CPF:");

        LbEnderecoCadastro.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbEnderecoCadastro.setText("Endereço:");

        InternaResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        InternaResultado.setVisible(true);

        LbNomeResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado.setText("Nome:");

        LbNomeResultado1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado1.setText("Email:");

        LbNomeResultado2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado2.setText("Endereço:");

        LbNomeResultado3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado3.setText("Telefone:");

        LbNomeResultado4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado4.setText("CPF:");

        LbNomeResultado5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbNomeResultado5.setText("Cadastrado em:");

        BarraProgresso.setForeground(new java.awt.Color(255, 0, 51));
        BarraProgresso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROGRESSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        BarraProgresso.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("RESULTADO:");

        javax.swing.GroupLayout InternaResultadoLayout = new javax.swing.GroupLayout(InternaResultado.getContentPane());
        InternaResultado.getContentPane().setLayout(InternaResultadoLayout);
        InternaResultadoLayout.setHorizontalGroup(
            InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaResultadoLayout.createSequentialGroup()
                        .addComponent(LbNomeResultado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoEmailResultado))
                    .addGroup(InternaResultadoLayout.createSequentialGroup()
                        .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addComponent(LbNomeResultado5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoResultadoCadastro))
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addComponent(LbNomeResultado4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoResultadoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addComponent(LbNomeResultado3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoTelefoneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addComponent(LbNomeResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNomeResultado))
                            .addGroup(InternaResultadoLayout.createSequentialGroup()
                                .addComponent(LbNomeResultado2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoEnderecoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
            .addGroup(InternaResultadoLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(BarraProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InternaResultadoLayout.setVerticalGroup(
            InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaResultadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado)
                    .addComponent(CampoNomeResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado1)
                    .addComponent(CampoEmailResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado3)
                    .addComponent(CampoTelefoneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado2)
                    .addComponent(CampoEnderecoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado4)
                    .addComponent(CampoResultadoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InternaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeResultado5)
                    .addComponent(CampoResultadoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(BarraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbEmailCadastro)
                                    .addComponent(LbNomeCadastro)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LbTelefoneCadastro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LbEnderecoCadastro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(CampoTelefoneCadastro)
                            .addComponent(CampoEmailCadastro)
                            .addComponent(CampoNomeCadastro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(LbCpfCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InternaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InternaEditarUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbNomeCadastro)
                            .addComponent(CampoNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbEmailCadastro)
                            .addComponent(CampoEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoTelefoneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbTelefoneCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbEnderecoCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbCpfCadastro))
                        .addGap(18, 18, 18)
                        .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InternaResultado))
                    .addComponent(InternaEditarUsuario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoTelefoneCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneCadastroActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        // 
    }//GEN-LAST:event_BtEditarActionPerformed

    private void CampoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisarActionPerformed

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        int linha = TabelaClientes.getSelectedRow();
        if (linha == -1) {
            return;
        }
        
    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void CampoInfoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInfoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInfoCPFActionPerformed

    public String GetIdUsuario() {
        return CampoInfoId.getText();
    }

    public String GetNome() {
        return CampoNomeCadastro.getText();
    }

    public String GetEmail() {
        return CampoEmailCadastro.getText();
    }

    public String GetCpf() {
        return CampoCpfCadastro.getText();
    }

    public String GetTelefone() {
        return CampoTelefoneCadastro.getText();
    }

    public String GetEndereco() {
        return CampoEndereco.getText();
    }

    public Map<String, String> InfoUsuarioEditar() {
        Map<String, String> dados = new HashMap<>();
        dados.put("id", CampoInfoId.getText());
        dados.put("Nome", CampoInfoNome.getText());
        dados.put("email", CampoInfoEmail.getText());
        dados.put("cpf", CampoInfoCPF.getText());
        dados.put("telefone", CampoInfoTelefone.getText());
        dados.put("endereco", CampoInfoEndereco.getText());
        dados.put("dataCadastro", CampoInfoDataCadastro.getText());
        dados.put("dataAtualizacao", CampoInfoDataAtualizacao.getText());
        return dados;
    }

    public javax.swing.JButton getBtSalvar() {
        return BtSalvar;
    }

    public javax.swing.JButton getBtExlcuir() {
        return BtExcluir;
    }

    public javax.swing.JButton getBtEditar() {
        return BtEditar;
    }

    public JProgressBar AtivarBarraProgresso() {
        return BarraProgresso;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgresso;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField CampoCpfCadastro;
    private javax.swing.JTextField CampoEmailCadastro;
    private javax.swing.JTextField CampoEmailResultado;
    private javax.swing.JTextField CampoEndereco;
    private javax.swing.JTextField CampoEnderecoResultado;
    private javax.swing.JTextField CampoInfoCPF;
    private javax.swing.JTextField CampoInfoDataAtualizacao;
    private javax.swing.JTextField CampoInfoDataCadastro;
    private javax.swing.JTextField CampoInfoEmail;
    private javax.swing.JTextField CampoInfoEndereco;
    private javax.swing.JTextField CampoInfoId;
    private javax.swing.JTextField CampoInfoNome;
    private javax.swing.JTextField CampoInfoTelefone;
    private javax.swing.JTextField CampoNomeCadastro;
    private javax.swing.JTextField CampoNomeResultado;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JTextField CampoResultadoCadastro;
    private javax.swing.JTextField CampoResultadoCpf;
    private javax.swing.JTextField CampoTelefoneCadastro;
    private javax.swing.JTextField CampoTelefoneResultado;
    private javax.swing.JLabel IconPesquisar;
    private javax.swing.JInternalFrame InternaDadosPesquisa;
    private javax.swing.JInternalFrame InternaEditarUsuario;
    private javax.swing.JInternalFrame InternaResultado;
    private javax.swing.JLabel LbCpfCadastro;
    private javax.swing.JLabel LbEmailCadastro;
    private javax.swing.JLabel LbEnderecoCadastro;
    private javax.swing.JLabel LbInfoCPF;
    private javax.swing.JLabel LbInfoDataAtualizacao;
    private javax.swing.JLabel LbInfoDataCadastro;
    private javax.swing.JLabel LbInfoEmail;
    private javax.swing.JLabel LbInfoEndereço;
    private javax.swing.JLabel LbInfoNome1;
    private javax.swing.JLabel LbInfoNome2;
    private javax.swing.JLabel LbInfotelefone;
    private javax.swing.JLabel LbNomeCadastro;
    private javax.swing.JLabel LbNomeResultado;
    private javax.swing.JLabel LbNomeResultado1;
    private javax.swing.JLabel LbNomeResultado2;
    private javax.swing.JLabel LbNomeResultado3;
    private javax.swing.JLabel LbNomeResultado4;
    private javax.swing.JLabel LbNomeResultado5;
    private javax.swing.JLabel LbTelefoneCadastro;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoPesquisar() {
        return CampoPesquisar;
    }

    public JTable getTabelaUsuarios() {
        return TabelaClientes;
    }

    public void RetornoDados(String Nome, String Email, String Telefone, String Endereco, String Cpf, String DataCadastro) {
        CampoNomeResultado.setText(Nome);
        CampoEmailResultado.setText(Email);
        CampoTelefoneResultado.setText(Telefone);
        CampoEnderecoResultado.setText(Endereco);
        CampoResultadoCpf.setText(Cpf);
        CampoResultadoCadastro.setText(DataCadastro);
    }

    public void InfoUsuario(String id, String nome, String email, String cpf, String telefone, String Endereco, String dataCadastro, String dataAtualizacao) {
         this.CampoInfoId.setText(id);
        this.CampoInfoNome.setText(nome);
        this.CampoInfoEmail.setText(email);
        this.CampoInfoTelefone.setText(telefone);
        this.CampoInfoCPF.setText(cpf);
        this.CampoInfoEndereco.setText(Endereco);
        this.CampoInfoDataCadastro.setText(dataCadastro);
        this.CampoInfoDataAtualizacao.setText(dataAtualizacao);
    }
}
